Add fast jet top tagger
iLCSoft/MarlinFastJet pull request #7
Opened 2017-05-04 16:17 UTC by lstroem

BEGINRELEASENOTES
- Updated instructions on how to use FastJetUtil.h in stand-alone project.
- Moved getRecPars to FastJetUtil to enable broader use of conversion between PseudoJet objects and ReconstructedParticle (renamed convertFromPseudoJet).
- Added FastJet JHTopTagger implementation and made changes in other files to accommodate such tool implementations.

ENDRELEASENOTES

2017-05-04 16:32 UTC, andresailer requested changes

2017-05-04 16:32 UTC, andresailer commented on CMakeLists.txt
> +# load fastjet util
Please remove these commented lines

2017-05-04 16:32 UTC, andresailer commented on src/FastJetClustering.cc
> +
Please remove the commented lines

2017-05-04 16:32 UTC, andresailer commented on src/FastJetTopTagger.cpp
> +			     std::string("0.05"));
Why are you not defining `_deltaP`, `_deltaR`, `_cos_theta_W_max` as doubles?

2017-05-04 16:36 UTC, andresailer commented on include/FastJetTopTagger.h
> +  FastJetTopTagger(const FastJetTopTagger& rhs);
```
FastJetTopTagger(const FastJetTopTagger& rhs) = delete;
FastJetTopTagger & operator = (const FastJetTopTagger&) = delete;
```
and remove the implementation of the copy constructor

2017-05-04 16:36 UTC, andresailer commented on include/FastJetTopTagger.h
> +  std::string _R;
Make them doubles

2017-05-04 18:08 UTC, lstroem commented
The requested changes have all been implemented. Updated files pushed to my fork.

2017-05-05 08:07 UTC, andresailer approved these changes

2017-05-05 08:08 UTC, merged